In [9]:
import numpy as np
import pandas as pd
import matplotlib

In [10]:
kepler = pd.read_csv('data/planets.csv')

In [11]:
kepler

,rowid,pl_hostname,pl_letter,pl_discmethod,pl_pnum,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,...,st_masserr1,st_masserr2,st_masslim,st_massblend,st_rad,st_raderr1,st_raderr2,st_radlim,st_radblend,rowupdate
0,1,11 Com,b,Radial Velocity,1,326.030000,0.320000,-0.320000,0.0,1.290000,...,0.30,-0.30,0.0,False,19.00,2.00,-2.00,False,False,2014-05-14
1,2,11 UMi,b,Radial Velocity,1,516.220000,3.250000,-3.250000,0.0,1.540000,...,0.25,-0.25,0.0,False,24.08,1.84,-1.84,False,False,2014-05-14
2,3,14 And,b,Radial Velocity,1,185.840000,0.230000,-0.230000,0.0,0.830000,...,0.10,-0.20,0.0,False,11.00,1.00,-1.00,False,False,2014-05-14
3,4,14 Her,b,Radial Velocity,1,1773.400000,2.500000,-2.500000,0.0,2.770000,...,0.05,-0.05,0.0,False,NaN,NaN,NaN,NaN,False,2014-05-14
4,5,16 Cyg B,b,Radial Velocity,1,798.500000,1.000000,-1.000000,0.0,1.681000,...,NaN,NaN,0.0,False,NaN,NaN,NaN,NaN,False,2015-09-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3367,3368,ups And,b,Radial Velocity,4,4.617033,0.000023,-0.000023,0.0,0.059222,...,NaN,NaN,0.0,False,1.56,NaN,NaN,False,False,2014-05-14
3368,3369,ups And,c,Radial Velocity,4,241.258000,0.064000,-0.064000,0.0,0.827774,...,NaN,NaN,0.0,False,1.56,NaN,NaN,False,False,2014-05-14
3369,3370,ups And,d,Radial Velocity,4,1276.460000,0.570000,-0.570000,0.0,2.513290,...,NaN,NaN,0.0,False,1.56,NaN,NaN,False,False,2014-05-14
3370,3371,ups And,e,Radial Velocity,4,3848.860000,0.740000,-0.740000,0.0,5.245580,...,NaN,NaN,0.0,False,1.56,NaN,NaN,False,False,2014-05-14
3371,3372,xi Aql,b,Radial Velocity,1,136.750000,0.250000,-0.250000,0.0,0.680000,...,NaN,NaN,0.0,False,12.00,NaN,NaN,False,False,2014-05-14

In [12]:
kepler.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3372 entries, 0 to 3371
Data columns (total 67 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rowid            3372 non-null   int64
 1   pl_hostname      3372 non-null   object
 2   pl_letter        3372 non-null   object
 3   pl_discmethod    3372 non-null   object
 4   pl_pnum          3372 non-null   int64
 5   pl_orbper        3305 non-null   float64
 6   pl_orbpererr1    3180 non-null   float64
 7   pl_orbpererr2    3180 non-null   float64
 8   pl_orbperlim     3304 non-null   float64
 9   pl_orbsmax       1897 non-null   float64
 10  pl_orbsmaxerr1   1020 non-null   float64
 11  pl_orbsmaxerr2   1019 non-null   float64
 12  pl_orbsmaxlim    1892 non-null   object
 13  pl_orbeccen      974 non-null    float64
 14  pl_orbeccenerr1  701 non-null    float64
 15  pl_orbeccenerr2  701 non-null    float64
 16  pl_orbeccenlim   971 non-null    float64
 17  pl_orbincl       502 non-null    float64
 18  pl_orbinclerr1   472 non-null    float64
 19  pl_orbinclerr2   474 non-null    float64
 20  pl_orbincllim    504 non-null    float64
 21  pl_bmassj        1174 non-null   float64
 22  pl_bmassjerr1    987 non-null    float64
 23  pl_bmassjerr2    987 non-null    float64
 24  pl_bmassjlim     1174 non-null   float64
 25  pl_bmassprov     1174 non-null   object
 26  pl_radj          2694 non-null   float64
 27  pl_radjerr1      2656 non-null   float64
 28  pl_radjerr2      2656 non-null   float64
 29  pl_radjlim       2694 non-null   object
 30  pl_dens          388 non-null    float64
 31  pl_denserr1      378 non-null    float64
 32  pl_denserr2      378 non-null    float64
 33  pl_denslim       387 non-null    float64
 34  pl_ttvflag       3372 non-null   bool
 35  pl_kepflag       3372 non-null   bool
 36  pl_k2flag        3372 non-null   bool
 37  pl_nnotes        3372 non-null   int64
 38  ra_str           3372 non-null   object
 39  ra               3372 non-null   float64
 40  dec_str          3372 non-null   object
 41  dec              3372 non-null   float64
 42  st_dist          2296 non-null   float64
 43  st_disterr1      2187 non-null   float64
 44  st_disterr2      2187 non-null   float64
 45  st_distlim       2293 non-null   float64
 46  st_optmag        3251 non-null   float64
 47  st_optmagerr     541 non-null    float64
 48  st_optmaglim     3251 non-null   object
 49  st_optmagblend   3251 non-null   object
 50  st_optband       3251 non-null   object
 51  st_teff          3205 non-null   float64
 52  st_tefferr1      3100 non-null   float64
 53  st_tefferr2      3021 non-null   float64
 54  st_tefflim       3204 non-null   object
 55  st_teffblend     3219 non-null   object
 56  st_mass          3051 non-null   float64
 57  st_masserr1      2458 non-null   float64
 58  st_masserr2      2380 non-null   float64
 59  st_masslim       3047 non-null   float64
 60  st_massblend     2977 non-null   object
 61  st_rad           3015 non-null   float64
 62  st_raderr1       2955 non-null   float64
 63  st_raderr2       2878 non-null   float64
 64  st_radlim        3014 non-null   object
 65  st_radblend      3185 non-null   object
 66  rowupdate        3372 non-null   object
dtypes: bool(3), float64(44), int64(3), object(17)
memory usage: 1.7+ MB

In [13]:
kepler.describe()

,rowid,pl_pnum,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,pl_orbeccen,...,st_teff,st_tefferr1,st_tefferr2,st_mass,st_masserr1,st_masserr2,st_masslim,st_rad,st_raderr1,st_raderr2
count,3372.000000,3372.000000,3.305000e+03,3.180000e+03,3.180000e+03,3304.000000,1897.000000,1020.000000,1019.000000,974.000000,...,3205.000000,3100.000000,3021.000000,3051.000000,2458.000000,2380.000000,3047.000000,3015.000000,2955.000000,2878.000000
mean,1686.500000,1.765421,2.725809e+03,1.254899e+03,-1.295899e+03,-0.000605,7.704206,0.572103,-0.596899,0.170790,...,5544.890983,104.926152,-107.783082,0.981776,0.076383,-0.068634,-0.001969,1.482036,0.251672,-0.183506
std,973.556881,1.120909,1.274303e+05,6.481581e+04,6.503400e+04,0.034794,89.695318,7.008368,7.368573,0.195816,...,1762.983040,61.395915,74.887149,0.309485,0.098892,0.068455,0.044339,3.168959,2.089418,0.836676
min,1.000000,1.000000,9.070629e-02,0.000000e+00,-3.650000e+06,-1.000000,0.004400,0.000000,-200.000000,0.000000,...,575.000000,5.000000,-2360.240000,0.020000,0.000000,-1.500000,-1.000000,0.040000,0.000000,-26.000000
25%,843.750000,1.000000,4.757940e+00,1.499500e-05,-7.092500e-04,0.000000,0.057900,0.000945,-0.040000,0.019000,...,5113.000000,63.950000,-137.000000,0.840000,0.040000,-0.080000,0.000000,0.810000,0.040000,-0.190000
50%,1686.500000,1.000000,1.279458e+01,7.502000e-05,-7.552000e-05,0.000000,0.122000,0.004000,-0.004000,0.106500,...,5626.000000,94.000000,-100.000000,0.970000,0.050000,-0.050000,0.000000,0.980000,0.100000,-0.080000
75%,2529.250000,2.000000,4.484098e+01,7.101000e-04,-1.500000e-05,0.000000,0.640000,0.040000,-0.000960,0.255977,...,5939.000000,128.522500,-62.340000,1.100000,0.080000,-0.040000,0.000000,1.230000,0.250000,-0.040000
max,3372.000000,7.000000,7.300000e+06,3.650000e+06,0.000000e+00,1.000000,2500.000000,200.000000,0.000000,0.956000,...,57000.000000,787.000000,-5.000000,3.900000,1.660000,0.000000,0.000000,51.100000,104.530000,0.000000

In [14]:
kepler.isna().sum()

rowid              0
pl_hostname        0
pl_letter          0
pl_discmethod      0
pl_pnum            0
                ...
st_raderr1       417
st_raderr2       494
st_radlim        358
st_radblend      187
rowupdate          0
Length: 67, dtype: int64

In [15]:
kepler.columns

Index(['rowid', 'pl_hostname', 'pl_letter', 'pl_discmethod', 'pl_pnum',
       'pl_orbper', 'pl_orbpererr1', 'pl_orbpererr2', 'pl_orbperlim',
       'pl_orbsmax', 'pl_orbsmaxerr1', 'pl_orbsmaxerr2', 'pl_orbsmaxlim',
       'pl_orbeccen', 'pl_orbeccenerr1', 'pl_orbeccenerr2', 'pl_orbeccenlim',
       'pl_orbincl', 'pl_orbinclerr1', 'pl_orbinclerr2', 'pl_orbincllim',
       'pl_bmassj', 'pl_bmassjerr1', 'pl_bmassjerr2', 'pl_bmassjlim',
       'pl_bmassprov', 'pl_radj', 'pl_radjerr1', 'pl_radjerr2', 'pl_radjlim',
       'pl_dens', 'pl_denserr1', 'pl_denserr2', 'pl_denslim', 'pl_ttvflag',
       'pl_kepflag', 'pl_k2flag', 'pl_nnotes', 'ra_str', 'ra', 'dec_str',
       'dec', 'st_dist', 'st_disterr1', 'st_disterr2', 'st_distlim',
       'st_optmag', 'st_optmagerr', 'st_optmaglim', 'st_optmagblend',
       'st_optband', 'st_teff', 'st_tefferr1', 'st_tefferr2', 'st_tefflim',
       'st_teffblend', 'st_mass', 'st_masserr1', 'st_masserr2', 'st_masslim',
       'st_massblend', 'st_rad', 'st_raderr1', 'st_raderr2', 'st_radlim',
       'st_radblend', 'rowupdate'],
      dtype='object')

In [31]:
kepler.st_teff

0       4742.0
1       4340.0
2       4813.0
3       5311.0
4       5674.0
         ...
3367       NaN
3368       NaN
3369       NaN
3370       NaN
3371    4780.0
Name: st_teff, Length: 3372, dtype: float64

In [26]:
kepler.pl_bmassj.isna().sum()

2198

In [47]:
kepler.pl_hostname[3350:3362]

3350      bet UMi
3351      eps CrB
3352      eps Eri
3353      eps Tau
3354    gam 1 Leo
3355      gam Cep
3356      kap And
3357      kap CrB
3358       mu Leo
3359       nu Oph
3360       nu Oph
3361      ome Ser
Name: pl_hostname, dtype: object

In [37]:
kepler.pl_orbper.t

0        326.030000
1        516.220000
2        185.840000
3       1773.400000
4        798.500000
           ...
3367       4.617033
3368     241.258000
3369    1276.460000
3370    3848.860000
3371     136.750000
Name: pl_orbper, Length: 3372, dtype: float64