In [2]:
import numpy as np
import pandas as pd

In [5]:
planets = pd.read_csv('NASA_planets.csv')

In [4]:
uniq_plan = [x.lower() for x in planets.pl_name.unique()]

NameError: name 'planets' is not defined

In [10]:
old_plan = pd.read_csv('data/planets.csv')

In [16]:
diff_planets = [x for x in old_plan.pl_hostname.unique() if x.lower() not in uniq_plan]

In [17]:
len(diff_planets)

2509

In [6]:
planets

,pl_name,sy_snum,sy_pnum,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,...,st_masserr1,st_masserr2,st_masslim,rastr,ra,decstr,dec,sy_dist,sy_disterr1,sy_disterr2
0,11 Com b,2,1,326.03000,0.32,-0.32,0.0,1.29000,0.05000,-0.05000,...,0.30,-0.30,0.0,12h20m42.91s,185.178779,+17d47m35.71s,17.793252,93.1846,1.92380,-1.92380
1,11 Com b,2,1,NaN,NaN,NaN,NaN,1.21000,0.06000,-0.05000,...,0.40,-0.30,0.0,12h20m42.91s,185.178779,+17d47m35.71s,17.793252,93.1846,1.92380,-1.92380
2,11 UMi b,1,1,NaN,NaN,NaN,NaN,1.51000,0.06000,-0.05000,...,0.40,-0.30,0.0,15h17m05.90s,229.274595,+71d49m26.19s,71.823943,125.3210,1.97650,-1.97650
3,11 UMi b,1,1,516.21997,3.20,-3.20,0.0,1.53000,0.07000,-0.07000,...,0.69,-0.69,0.0,15h17m05.90s,229.274595,+71d49m26.19s,71.823943,125.3210,1.97650,-1.97650
4,11 UMi b,1,1,516.22000,3.25,-3.25,0.0,1.54000,0.07000,-0.07000,...,0.25,-0.25,0.0,15h17m05.90s,229.274595,+71d49m26.19s,71.823943,125.3210,1.97650,-1.97650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29362,ups And d,2,3,1278.10000,2.90,-2.90,0.0,2.53000,0.15000,-0.15000,...,0.16,-0.14,0.0,01h36m47.60s,24.198353,+41d24m13.73s,41.403815,13.4054,0.06350,-0.06290
29363,ups And d,2,3,1276.46000,0.57,-0.57,0.0,2.51329,0.00075,-0.00075,...,NaN,NaN,0.0,01h36m47.60s,24.198353,+41d24m13.73s,41.403815,13.4054,0.06350,-0.06290
29364,ups And d,2,3,1319.00000,18.00,-18.00,0.0,2.57000,NaN,NaN,...,NaN,NaN,NaN,01h36m47.60s,24.198353,+41d24m13.73s,41.403815,13.4054,0.06350,-0.06290
29365,xi Aql b,1,1,NaN,NaN,NaN,NaN,0.58000,0.02000,-0.03000,...,0.20,-0.20,0.0,19h54m14.99s,298.562449,+08d27m39.98s,8.461105,56.1858,0.55975,-0.55975
29366,xi Aql b,1,1,136.75000,0.25,-0.25,0.0,0.68000,NaN,NaN,...,NaN,NaN,0.0,19h54m14.99s,298.562449,+08d27m39.98s,8.461105,56.1858,0.55975,-0.55975

In [7]:
planets.columns

Index(['pl_name', 'sy_snum', 'sy_pnum', 'pl_orbper', 'pl_orbpererr1',
       'pl_orbpererr2', 'pl_orbperlim', 'pl_orbsmax', 'pl_orbsmaxerr1',
       'pl_orbsmaxerr2', 'pl_orbsmaxlim', 'pl_bmasse', 'pl_bmasseerr1',
       'pl_bmasseerr2', 'pl_bmasselim', 'pl_bmassj', 'pl_bmassjerr1',
       'pl_bmassjerr2', 'pl_bmassjlim', 'pl_bmassprov', 'st_spectype',
       'st_teff', 'st_tefferr1', 'st_tefferr2', 'st_tefflim', 'st_mass',
       'st_masserr1', 'st_masserr2', 'st_masslim', 'rastr', 'ra', 'decstr',
       'dec', 'sy_dist', 'sy_disterr1', 'sy_disterr2'],
      dtype='object')

In [8]:
planets.st_spectype.unique()

array(['G8 III', nan, 'K4 III', 'K0 III', 'K0 V', 'G2.5 V', 'G3 V',
       'G6 III', 'K7 V', 'G3 IV', 'M5.5/M6', 'M3.5 V', 'M6', 'M8.5', 'M8',
       'F6 V', 'K1 III', 'K1.5 III', 'G1 V', 'G0 V', 'F0 IV', 'G8 V',
       'K0 IV-V', 'K0 IV', 'G5 V', 'G3 III', 'K0', 'G5 III', 'K2 V',
       'K2 II', 'K5 III', 'G', 'K7/M0 V', 'K3 V', 'K5 V', 'M3.5', 'K7',
       'K1 V', 'F9 V', 'G2 V', 'G9 V', 'F8 IV', 'F9', 'G5', 'G2',
       'G8/9 IV', 'F3 V', 'G2 IV', 'G0 VI', 'L1.5', 'M0.5', 'F8 V',
       'F5 V', 'G6 V', 'G0', 'K3', 'G8 IV/V', 'M7.25', 'M2.5 V', 'M5.5 V',
       'M4.5 V', 'M3', 'K4.5', 'M2 V', 'M1', 'M0 V', 'M1/M2 V', 'M3.0 V',
       'M0.5 V', 'M0', 'M2.5', 'M4', 'M0.0 V', 'M1.5', 'M4.0 V', 'M1.9',
       'M1.5 V', 'M4.0', 'M3.5 Ve', 'M1 V', 'M3 V', 'M2', 'M4 V', 'K6 V',
       'M1.0 V', 'K4', 'G4', 'F', 'F8', 'K', 'K2', 'K1', 'G3', 'G8',
       'A8 V', 'G V', 'K V', 'F V', 'B9 Vne', 'G9 III', 'K2 IV', 'G5 IV',
       'K2 III', 'K9 V', 'G4 IV', 'G7 III', 'G7 V', 'K4 V', 'G4 V',
       'G2/G3 V', 'G1 IV', 'F5', 'G0 IV', 'G6', 'F8 IV/V', 'K1 IV',
       'K3.5 V', 'F7 V', 'G5 IV/V', 'G8 IV', 'K2.5 V', 'K3 IV', 'K0-2 V',
       'G6 IV', 'G3 IV-V', 'G3 V/IV', 'K0 III-IV', 'G2/G3 IV/V', 'M1 III',
       'K3/4 IV', 'M2 III', 'F9 IV/V', 'K5', 'K3 III', 'G1 IV/V',
       'K4.5 V', 'G3/G5 V', 'G4 IV-V', 'G1.5 V', 'G8/K0', 'G8-K0',
       'K1 IV-V', 'F6 IV', 'G1-1.5 V', 'K0.5 V', 'G2/G3', 'A8 III',
       'Be9.5/AO', 'M0.5 Ve', 'A2 V', 'B9 V', 'K2 III/IV', 'A5', 'F9 IV',
       'K5.5', 'M0.0', 'M4.5', 'G7 IV/V', 'M0.0&plusmn;0.5',
       'M(3.5+/-0.5) V', 'M3.3', 'K7.5 V', 'M3.0', 'A', 'F4 V', 'A2',
       'B9.5-A0', 'M', 'B', 'F7 IV', 'F5 IV', 'G9/K0', 'G0 IV-V', 'M5',
       'M(6.1+/-0.7) V', 'A8', 'A7 V', 'WD', 'M2-M7', 'M V', 'M9',
       'G9 IV', 'G0/F9 V', 'M7.0 V', 'M7', 'M7.5', 'F2', 'F6', 'K6', 'G1',
       'F7', 'F1 V', 'F4', 'A1 IV-V', 'F6 IV-V', 'G9', 'G7', 'K7-M0 V',
       'T8.5', 'M3/3.5 V', 'B9 IV'], dtype=object)

In [9]:
final_planets = planets.groupby('pl_name').mean().reset_index()

In [10]:
pl_name = final_planets.pl_name.unique()

In [11]:
for name in pl_name:
    try:
        final_planets.loc[final_planets.pl_name == name, 'spec_type'] = planets.loc[planets.pl_name == name, 'st_spectype'].dropna().values[0]
    except:
        final_planets.loc[final_planets.pl_name == name, 'spec_type'] = np.nan

In [12]:
final_planets.loc[final_planets.pl_orbsmax.isna()]

,pl_name,sy_snum,sy_pnum,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,...,st_mass,st_masserr1,st_masserr2,st_masslim,ra,dec,sy_dist,sy_disterr1,sy_disterr2,spec_type
16,2MASS J21402931+1625183 A b,1,1,7336.500000,1934.500000,-584.000000,0.0,NaN,NaN,NaN,...,0.080,0.060,-0.060,0.0,325.121821,16.421341,NaN,NaN,NaN,M8.5
66,CI Tau b,1,1,8.989100,0.020200,-0.020200,0.0,NaN,NaN,NaN,...,0.900,0.020,-0.020,0.0,68.466769,22.841619,157.9980,1.1980,-1.1800,K7
112,DS Tuc A b,2,1,8.138396,0.000197,-0.000197,0.0,NaN,NaN,NaN,...,0.985,0.045,-0.045,0.0,354.915467,-69.196043,44.0622,0.0693,-0.0691,G6 V
114,EPIC 201238110 b,1,1,28.167600,0.003250,-0.003550,0.0,NaN,NaN,NaN,...,0.410,0.110,-0.050,0.0,179.705853,-3.389461,159.2590,1.4140,-1.3900,NaN
115,EPIC 201497682 b,1,1,2.131740,0.000220,-0.000220,0.0,NaN,NaN,NaN,...,0.780,0.090,-0.170,0.0,168.936679,0.488061,253.0260,1.6640,-1.6640,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3922,NY Vir c,2,2,8799.000000,240.000000,-240.000000,0.0,NaN,NaN,NaN,...,0.460,0.010,-0.010,0.0,204.700585,-2.030387,544.0240,18.8765,-18.8765,NaN
4023,SR 12 AB c,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,246.831236,-24.694669,NaN,NaN,NaN,NaN
4088,TOI-837 b,1,1,8.324876,0.000016,-0.000016,0.0,NaN,NaN,NaN,...,1.120,0.060,-0.060,0.0,157.037281,-64.505211,142.4880,0.4610,-0.4580,G0/F9 V
4139,WASP-107 c,1,2,1088.000000,15.000000,-16.000000,0.0,NaN,NaN,NaN,...,0.680,0.020,-0.020,0.0,188.386428,-10.146214,64.7414,0.2617,-0.2596,NaN
4152,WASP-126 c,1,2,7.630000,0.170000,-0.170000,0.0,NaN,NaN,NaN,...,1.120,NaN,NaN,0.0,63.374706,-69.226593,216.5260,0.9360,-0.9280,NaN

In [13]:
final_planets.spec_type.isna().sum()

3140

In [14]:
final_planets.columns

Index(['pl_name', 'sy_snum', 'sy_pnum', 'pl_orbper', 'pl_orbpererr1',
       'pl_orbpererr2', 'pl_orbperlim', 'pl_orbsmax', 'pl_orbsmaxerr1',
       'pl_orbsmaxerr2', 'pl_orbsmaxlim', 'pl_bmasse', 'pl_bmasseerr1',
       'pl_bmasseerr2', 'pl_bmasselim', 'pl_bmassj', 'pl_bmassjerr1',
       'pl_bmassjerr2', 'pl_bmassjlim', 'st_teff', 'st_tefferr1',
       'st_tefferr2', 'st_tefflim', 'st_mass', 'st_masserr1', 'st_masserr2',
       'st_masslim', 'ra', 'dec', 'sy_dist', 'sy_disterr1', 'sy_disterr2',
       'spec_type'],
      dtype='object')

In [15]:
planets.loc[planets.pl_name == 'xi Aql b', 'st_spectype']

29365    NaN
29366    NaN
Name: st_spectype, dtype: object

In [16]:
final_planets.st_teff.isna().sum()

216

In [17]:
nan_stellar_t = final_planets[final_planets.st_teff.isna()]

In [18]:
nan_stellar_t

,pl_name,sy_snum,sy_pnum,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,...,st_mass,st_masserr1,st_masserr2,st_masslim,ra,dec,sy_dist,sy_disterr1,sy_disterr2,spec_type
10,2MASS J01033563-5515561 AB b,2,1,NaN,NaN,NaN,NaN,84.000,NaN,NaN,...,0.19,0.02,-0.02,0.0,15.899249,-55.265829,NaN,NaN,NaN,M5.5/M6
13,2MASS J04414489+2301513 b,1,1,NaN,NaN,NaN,NaN,15.000,NaN,NaN,...,0.02,NaN,NaN,0.0,70.437108,23.030854,NaN,NaN,NaN,M8.5
15,2MASS J19383260+4603591 b,2,1,416.00,2.00,-2.00,0.0,0.920,0.020,-0.020,...,0.48,0.03,-0.03,0.0,294.635917,46.066408,396.33200,6.38850,-6.38850,NaN
42,AB Pic b,1,1,NaN,NaN,NaN,NaN,260.000,NaN,NaN,...,NaN,NaN,NaN,NaN,94.803921,-58.054118,50.04750,0.07350,-0.07330,K2 V
65,CHXR 73 b,1,1,NaN,NaN,NaN,NaN,210.000,NaN,NaN,...,0.35,NaN,NaN,0.0,166.619399,-77.625872,190.37400,6.64700,-6.22000,M3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,eps Ind A b,3,1,16510.00,2100.00,-1740.00,0.0,11.550,0.980,-0.860,...,0.75,0.04,-0.04,0.0,330.871402,-56.796902,3.63857,0.00333,-0.00333,K2 V
4355,tau Cet e,1,4,162.87,1.08,-0.46,0.0,0.538,0.060,-0.060,...,0.78,0.01,-0.01,0.0,26.009303,-15.933799,3.60304,0.00678,-0.00675,NaN
4356,tau Cet f,1,4,636.13,11.70,-47.69,0.0,1.334,0.017,-0.044,...,0.78,0.01,-0.01,0.0,26.009303,-15.933799,3.60304,0.00678,-0.00675,NaN
4357,tau Cet g,1,4,20.00,0.02,-0.01,0.0,0.133,0.001,-0.002,...,0.78,0.01,-0.01,0.0,26.009303,-15.933799,3.60304,0.00678,-0.00675,NaN
4358,tau Cet h,1,4,49.41,0.08,-0.10,0.0,0.243,0.003,-0.003,...,0.78,0.01,-0.01,0.0,26.009303,-15.933799,3.60304,0.00678,-0.00675,NaN

In [19]:
spectral_type =  {'M5.5/M6': 2950,
        'M8.5': 2700,
         np.nan: np.nan,
        'K2 V': 4960,
        'M3.5': 3500,
        'K7': 4000,
        'L1.5': 2400,
        'M2.5': 3600,
        'M3.5 Ve': 3500,
        'M0 V': 3750,
        'M4.5 V': 3400,
        'M3': 3500,
        'G6 V': 5570,
        'K0': 5240,
        'G0': 6050,
        'G1 V': 5930,
        'G8 V': 5440,
        'G8': 5440,
        'G4 V': 5690,
        'G4 IV-V': 5700,
        'M2 V': 3600,
        'M0': 3750,
        'M0.5 Ve': 3800,
        'F5 V': 6700,
        'F7 V': 6400,
        'M': 3225,
        'K': 4620,
        'M2-M7': 3250,
        'K5': 4400,
        'G5 V': 5660,
        'M V': 3225}

In [20]:


final_planets.loc[(final_planets.st_teff.isna()) , 'st_teff'] = \
final_planets.loc[final_planets.st_teff.isna(), 'spec_type'].apply(lambda x: spectral_type[x])

In [21]:
final_planets

,pl_name,sy_snum,sy_pnum,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,...,st_mass,st_masserr1,st_masserr2,st_masslim,ra,dec,sy_dist,sy_disterr1,sy_disterr2,spec_type
0,11 Com b,2,1,326.030000,0.320000,-0.320000,0.0,1.250000,0.055000,-0.050000,...,2.650000,0.350000,-0.300000,0.0,185.178779,17.793252,93.1846,1.92380,-1.92380,G8 III
1,11 UMi b,1,1,516.219985,3.225000,-3.225000,0.0,1.526667,0.066667,-0.063333,...,2.093333,0.446667,-0.413333,0.0,229.274595,71.823943,125.3210,1.97650,-1.97650,K4 III
2,14 And b,1,1,185.840000,0.230000,-0.230000,0.0,0.755000,0.030000,-0.060000,...,1.700000,0.250000,-0.250000,0.0,352.824150,39.235837,75.4392,0.71400,-0.71400,K0 III
3,14 Her b,1,1,1766.640004,15.825000,-15.825000,0.0,2.819000,0.065000,-0.065000,...,0.922000,0.090000,-0.065000,0.0,242.602101,43.816362,17.9323,0.00730,-0.00730,K0 V
4,16 Cyg B b,3,1,799.360000,2.980000,-2.980000,0.0,1.660200,0.046750,-0.046750,...,1.025000,0.080000,-0.070000,0.0,295.465642,50.516824,21.1397,0.01100,-0.01110,G2.5 V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4359,tau Gem b,1,1,305.250000,0.100000,-0.100000,0.0,1.170000,NaN,NaN,...,2.300000,0.300000,-0.300000,0.0,107.784723,30.244954,112.5370,4.25300,-3.95900,K2 III
4360,ups And b,2,3,4.615874,0.001044,-0.001044,0.0,0.058744,0.001467,-0.001467,...,1.216667,0.160000,-0.140000,0.0,24.198353,41.403815,13.4054,0.06350,-0.06290,F8 V
4361,ups And c,2,3,240.552000,0.233500,-0.233500,0.0,0.827693,0.019338,-0.019338,...,1.225000,0.160000,-0.140000,0.0,24.198353,41.403815,13.4054,0.06350,-0.06290,F8 V
4362,ups And d,2,3,1287.040000,6.617500,-6.617500,0.0,2.530822,0.063583,-0.063583,...,1.225000,0.160000,-0.140000,0.0,24.198353,41.403815,13.4054,0.06350,-0.06290,F8 V
4363,xi Aql b,1,1,136.750000,0.250000,-0.250000,0.0,0.630000,0.020000,-0.030000,...,1.800000,0.200000,-0.200000,0.0,298.562449,8.461105,56.1858,0.55975,-0.55975,NaN

In [22]:
final_planets['pl_orbper_yrs'] = final_planets['pl_orbper'] / 365.25

In [23]:
final_planets.loc[final_planets.pl_orbper.isna()]

,pl_name,sy_snum,sy_pnum,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,...,st_masserr1,st_masserr2,st_masslim,ra,dec,sy_dist,sy_disterr1,sy_disterr2,spec_type,pl_orbper_yrs
6,1RXS J160929.1-210524 b,1,1,NaN,NaN,NaN,NaN,330.0,NaN,NaN,...,0.165,-0.1025,0.000000,242.376234,-21.083140,139.1350,1.3320,-1.3070,K7 V,NaN
10,2MASS J01033563-5515561 AB b,2,1,NaN,NaN,NaN,NaN,84.0,NaN,NaN,...,0.020,-0.0200,0.000000,15.899249,-55.265829,NaN,NaN,NaN,M5.5/M6,NaN
11,2MASS J01225093-2439505 b,1,1,NaN,NaN,NaN,NaN,52.0,6.0,-6.0,...,0.035,-0.0350,0.000000,20.712801,-24.664613,33.8281,0.0864,-0.0860,M3.5 V,NaN
12,2MASS J02192210-3925225 b,1,1,NaN,NaN,NaN,NaN,156.0,10.0,-10.0,...,0.010,-0.0100,0.000000,34.842705,-39.423077,NaN,NaN,NaN,M6,NaN
13,2MASS J04414489+2301513 b,1,1,NaN,NaN,NaN,NaN,15.0,NaN,NaN,...,NaN,NaN,0.000000,70.437108,23.030854,NaN,NaN,NaN,M8.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4120,USco1621 b,1,1,NaN,NaN,NaN,NaN,2880.0,20.0,-20.0,...,0.080,-0.0800,0.000000,245.373086,-25.495427,137.9010,0.9730,-0.9600,M2.5 V,NaN
4129,VHS J125601.92-125723.9 b,2,1,NaN,NaN,NaN,NaN,102.0,9.0,-9.0,...,0.020,-0.0100,-0.666667,194.008964,-12.956031,NaN,NaN,NaN,M7.5,NaN
4304,WD 0806-661 b,1,1,NaN,NaN,NaN,NaN,2500.0,NaN,NaN,...,NaN,NaN,NaN,121.727568,-66.305883,19.2444,0.0073,-0.0073,NaN,NaN
4306,WISEP J121756.91+162640.2 A b,1,1,NaN,NaN,NaN,NaN,8.0,1.3,-1.3,...,0.010,-0.0100,0.000000,184.487125,16.444500,NaN,NaN,NaN,T8.5,NaN
4342,kap And b,1,1,NaN,NaN,NaN,NaN,58.0,26.0,-11.0,...,0.125,-0.1250,0.000000,355.102597,44.333851,50.0177,0.8766,-0.8474,B9 IV,NaN

In [24]:
final_planets.dropna(subset = ['pl_orbper'], inplace = True)

In [46]:
final_planets.loc[final_planets.pl_orbsmax.isna(), 'pl_orbsmax'] = \
final_planets.loc[final_planets.pl_orbsmax.isna(), 'pl_orbper_yrs'].apply(lambda x: (x**2)**(1./ 3.))

In [47]:
final_planets.columns

Index(['pl_name', 'sy_snum', 'sy_pnum', 'pl_orbper', 'pl_orbsmax',
       'pl_orbsmaxlim', 'pl_bmasse', 'pl_bmassj', 'st_teff', 'st_mass', 'ra',
       'dec', 'sy_dist', 'spec_type', 'pl_orbper_yrs'],
      dtype='object')

In [48]:
final_planets.drop(columns = ['pl_orbpererr1', 'pl_orbpererr2', 'pl_orbperlim', 'pl_orbsmaxerr1', 'pl_orbsmaxerr2', 'pl_bmasseerr1', 'pl_bmasseerr2', 'pl_bmasselim', 'pl_bmassjerr1', 'pl_bmassjerr2','pl_bmassjlim', 'st_tefferr1','st_tefferr2','st_tefflim','st_masserr1','st_masserr2','st_masslim','sy_disterr1','sy_disterr2'], inplace = True)

KeyError: "['pl_orbpererr1' 'pl_orbpererr2' 'pl_orbperlim' 'pl_orbsmaxerr1'\n 'pl_orbsmaxerr2' 'pl_bmasseerr1' 'pl_bmasseerr2' 'pl_bmasselim'\n 'pl_bmassjerr1' 'pl_bmassjerr2' 'pl_bmassjlim' 'st_tefferr1'\n 'st_tefferr2' 'st_tefflim' 'st_masserr1' 'st_masserr2' 'st_masslim'\n 'sy_disterr1' 'sy_disterr2'] not found in axis"

In [61]:
final_planets.loc[final_planets.st_teff.isna(), 'pl_name']

15      2MASS J19383260+4603591 b
80                     CoRoT-20 c
102                      DE CVn b
111                      DP Leo b
114              EPIC 201238110 b
                  ...
4334                    eps Eri b
4355                    tau Cet e
4356                    tau Cet f
4357                    tau Cet g
4358                    tau Cet h
Name: pl_name, Length: 76, dtype: object

In [62]:
final_planets.loc[final_planets.st_teff.isna(), 'pl_name'].values[0:76]

array(['2MASS J19383260+4603591 b', 'CoRoT-20 c', 'DE CVn b', 'DP Leo b',
       'EPIC 201238110 b', 'EPIC 201497682 b', 'EPIC 201615463 c',
       'EPIC 201754305 d', 'EPIC 201833600 c', 'EPIC 206024342 b',
       'EPIC 206032309 b', 'EPIC 206042996 b', 'EPIC 206215704 b',
       'EPIC 206317286 b', 'EPIC 212297394 b', 'EPIC 212424622 b',
       'EPIC 212499991 b', 'EPIC 212587672 b', 'EPIC 220554210 c',
       'GJ 163 b', 'GJ 163 c', 'GJ 163 d', 'GJ 180 d', 'GJ 2056 b',
       'GJ 229 A c', 'GJ 3082 b', 'GJ 433 d', 'GJ 676 A c', 'GJ 687 c',
       'HD 102329 c', 'HD 114783 c', 'HD 116029 c', 'HD 156279 c',
       'HD 177565 b', 'HD 33142 c', 'HD 41004 A b', 'HD 47186 c',
       'HD 73526 c', 'HD 99706 c', 'HIP 4845 b', 'HU Aqr AB b',
       'HU Aqr AB c', 'HW Vir b', 'IC 4651 9122 b', 'K2-32 e',
       'Kepler-448 c', 'Kepler-47 d', 'Kepler-65 e', 'Kepler-82 f',
       'MOA-2009-BLG-266L b', 'MOA-2009-BLG-387L b',
       'MOA-2011-BLG-293L b', 'MXB 1658-298 b', 'OGLE-2005-BLG-390L b',
       'OGLE-2006-BLG-109L b', 'OGLE-2006-BLG-109L c',
       'OGLE-2016-BLG-1190L b', 'PSR B0329+54 b', 'PSR B1257+12 b',
       'PSR B1257+12 c', 'PSR B1257+12 d', 'PSR J2322-2650 b',
       'SWEEPS-11 b', 'SWEEPS-4 b', 'UZ For b', 'UZ For c', 'V1298 Tau c',
       'V1298 Tau d', 'V1298 Tau e', 'WASP-8 c', 'bet Pic c', 'eps Eri b',
       'tau Cet e', 'tau Cet f', 'tau Cet g', 'tau Cet h'], dtype=object)

In [ ]:
eff_surf_temp = {'2MASS J19383260+4603591 b': 33500.00,
                 'CoRoT-20 c': 5880.00,
                 'DE CVn b': 5745.00,
                 'DP Leo b': 3500.00,
                 'EPIC 201238110 b': 3587.00,
                 'EPIC 201497682 b': 4670.3500,
                 'EPIC 201615463 c': 3300.00,
                 'EPIC 201754305 d': 4761.00,
                 'EPIC 201833600 c': 3300.00,
                 'EPIC 206024342 b': 5800.00,
                 'EPIC 206032309 b': 3225.00,
                 'EPIC 206042996 b': 4800.00,
                 'EPIC 206215704 b': 3225.00,
                 'EPIC 206317286 b': 4800.00, 
                 'EPIC 212297394 b': 3700.00,
                 'EPIC 212424622 b': 5776.00,
                 'EPIC 212499991 b': 4730.00,
                 'EPIC 212587672 b': 5776.00,
                 'EPIC 220554210 c': 5776.00,
                 'GJ 163 b': 3300.00,
                 'GJ 163 c':
                  'GJ 163 d':
                  'GJ 180 d':
                 'GJ 2056 b':
                'GJ 229 A c':
                 'GJ 3082 b':
                  'GJ 433 d':
                'GJ 676 A c':
                  'GJ 687 c':
               'HD 102329 c':
               'HD 114783 c':
               'HD 116029 c':
               'HD 156279 c':
               'HD 177565 b':
                'HD 33142 c':
              'HD 41004 A b':
                'HD 47186 c':
                'HD 73526 c':
                'HD 99706 c':
                'HIP 4845 b':
              'HU Aqr AB b':
              'HU Aqr AB c':
                 'HW Vir b':
           'IC 4651 9122 b':
                  'K2-32 e':
             'Kepler-448 c':
              'Kepler-47 d':
              'Kepler-65 e':
              'Kepler-82 f':
      'MOA-2009-BLG-266L b':
      'MOA-2009-BLG-387L b':
      'MOA-2011-BLG-293L b':
           'MXB 1658-298 b':
     'OGLE-2005-BLG-390L b':
     'OGLE-2006-BLG-109L b':
     'OGLE-2006-BLG-109L c':
    'OGLE-2016-BLG-1190L b':
           'PSR B0329+54 b':
           'PSR B1257+12 b':
           'PSR B1257+12 c':
           'PSR B1257+12 d':
         'PSR J2322-2650 b':
              'SWEEPS-11 b':
               'SWEEPS-4 b':
                 'UZ For b':
                 'UZ For c':
             'V1298 Tau c':
              'V1298 Tau d':
              'V1298 Tau e':
                 'WASP-8 c':
                'bet Pic c':
                'eps Eri b':
                'tau Cet e':
                'tau Cet f':
                'tau Cet g':
                'tau Cet h':